[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
internal_port = 5050

# Configure Python version and system packages
[variables]
NIXPACKS_PYTHON_VERSION = "3.9"
NIXPACKS_APT_PKGS = "tesseract-ocr"

[[services]]
name = "analyzer-backend"
protocol = "http"

[[services.env]]
key = "PORT"
value = "5050"

[[services.env]]
key = "RAILWAY_ENVIRONMENT"
value = "production"

[[services.ports]]
port = 80
handlers = ["http"] 