[build]
builder = "nixpacks"
watchPatterns = ["**/*.py", "requirements.txt", "test-requirements.txt"]
buildCommand = "pip install -r test-requirements.txt"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[nixpacks]
enable-system-linker = true

# Configure Python version and system packages
[variables]
NIXPACKS_PYTHON_VERSION = "3.9"
NIXPACKS_APT_PKGS = "tesseract-ocr"

[[services]]
name = "analyzer-backend"
internal_port = 5050
protocol = "http"

[[services.ports]]
port = 80
handlers = ["http"] 